name: Build and publish to gh-pages

on:
  push:
    branches: [ main ]   # change to master if needed
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
          # If you ever want the action to use the PAT for checkout, set:
          # token: ${{ secrets.DEPLOY_TOKEN }}

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Cache gems
        uses: actions/cache@v4
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-gems-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-gems-

      - name: Install gems
        run: |
          gem install bundler
          bundle config set --local path 'vendor/bundle'
          bundle install --jobs 4 --retry 3

      - name: Build site (Jekyll)
        run: |
          bundle exec jekyll build --destination _site
          ls -la _site || (echo "_site missing — build failed" && exit 1)

      - name: Run htmlproofer (link-check) — non-failing
        run: |
          if bundle exec htmlproofer ./_site --assume_extension --internal-domains cyber-maya.github.io; then
            echo "htmlproofer passed"
          else
            echo "htmlproofer found issues — continuing to deploy"
          fi

      - name: Deploy to gh-pages (using PAT)
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./_site
          publish_branch: gh-pages
          personal_token: ${{ secrets.DEPLOY_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: '41898282+github-actions[bot]@users.noreply.github.com'
          keep_files: false
          allow_empty_commit: false

